/**
 * Локализация — полный словарь RU/EN
 */

const translations = {
  ru: {
    // Menu
    mainTitle: 'Roll Assistant',
    mainSubtitle: 'Создай своего героя',
    btnCreate: '✨ Создать персонажа',
    btnQuickStart: '⚡ Быстрый старт',
    btnCharacters: '👥 Мои персонажи',
    // Creation screen
    creationTitle: '🧙 Создание персонажа',
    back: '← Назад',
    saveCharacter: '💾 Сохранить персонажа',
    nameLabel: 'Имя персонажа',
    namePlaceholder: 'Введите имя',
    raceLabel: 'Раса',
    raceSelect: '-- Выберите расу --',
    raceDetails: '🔍 Подробности расы',
    classLabel: 'Класс',
    classSelect: '-- Выберите класс --',
    classDetails: '🔍 Подробности класса',
    subclassLabel: 'Архетип (Подкласс)',
    subclassSelect: '-- Выберите архетип --',
    levelLabel: 'Уровень персонажа',
    statsLabel: 'Характеристики',
    statsInfoBtn: '?⃝',
    pointsDisplay: 'Очки: %1 (базовые), +%2 от уровней',
    randomStats: '🎲 Случайно',
    resetStats: '🔄 Сбросить к 8',
    abilitiesLabel: '📜 Способности',
    abilitiesSummary: 'Не выбрано',
    abilitiesSelected: 'Выбрано: %1',
    btnOpenSpells: 'Выбрать способности',
    equipmentLabel: '⚔️ Снаряжение и артефакты',
    equipSearch: '🔍 Найти предмет...',
    equipAllTypes: 'Все типы',
    equipWeapon: '⚔️ Оружие',
    equipArmor: '🛡️ Доспех',
    equipArtifact: '💍 Артефакт',
    equipAllRarities: 'Все редкости',
    equipSelectItem: '-- Выберите предмет --',
    // Sheet
    sheetTitle: '📋 Карточка персонажа',
    sheetIdentity: 'Идентификация',
    sheetRace: 'Раса',
    sheetClass: 'Класс',
    sheetLevelHP: 'Уровень и хиты',
    sheetLevel: 'Уровень',
    sheetMaxHP: 'Макс. HP',
    sheetExp: 'Опыт',
    sheetAbilities: 'Характеристики',
    sheetCombat: 'Боевые параметры',
    sheetHP: 'HP',
    sheetAC: 'КД',
    sheetInitiative: 'Инициатива',
    sheetSpeed: 'Скорость',
    sheetProfBonus: 'Бонус мастерства',
    sheetSaves: 'Спасброски',
    sheetSkills: 'Навыки',
    sheetSkillsWip: 'В разработке',
    sheetEquipment: 'Экипировка',
    sheetEquipBonuses: '✨ Бонусы предметов',
    sheetBackpack: '🎒 Рюкзак',
    sheetSpells: 'Способности',
    sheetSelectSpells: '📜 Выбрать способности',
    sheetNoEquipped: 'Нет надетых предметов',
    sheetNoSpells: 'Нет выбранных способностей',
    sheetBackpackEmpty: 'Рюкзак пуст',
    // Equipment slots
    slotHead: 'Голова',
    slotBody: 'Тело',
    slotMainhand: 'Правая рука',
    slotOffhand: 'Левая рука',
    slotFeet: 'Ноги',
    slotRing: 'Кольцо',
    slotNeck: 'Шея',
    slotBack: 'Спина',
    slotHands: 'Руки',
    slotWaist: 'Пояс',
    // Backpack
    coinCopper: 'Медь',
    coinSilver: 'Серебро',
    coinGold: 'Золото',
    coinDiamond: 'Алмазы',
    grayChest: '🗝️ Серый сундук',
    goldChest: '🔱 Золотой сундук',
    addRecord: '📝 Добавить запись',
    btnEquip: 'Надеть',
    btnUnequip: 'Снять',
    // Characters list
    charactersListTitle: '👥 Мои персонажи',
    noSaved: 'Нет сохранённых персонажей',
    setMain: '⭐ Сделать основным',
    deleteChar: '🗑️ Удалить',
    mainBadge: '⭐ Основной',
    // Alerts
    charSaved: 'Персонаж «%1» сохранён!',
    success: 'Успех',
    error: 'Ошибка',
    confirm: 'Подтверждение',
    loaded: 'Загружено',
    done: 'Готово',
    quickStartConfirm: 'Будут созданы 6 сбалансированных персонажей 1-го уровня с оружием, доспехами и способностями. Продолжить?',
    quickStartDone: '6 персонажей добавлены в список «Мои персонажи». Последний выбран основным.',
    errorSelectRaceClass: 'Сначала выберите расу и класс!',
    confirmDelete: 'Удалить персонажа?',
    charLoaded: 'Персонаж загружен как основной!',
    mainChanged: 'Основной персонаж изменён!',
    slotOccupied: 'Слот занят',
    slotRingFull: 'Уже надето два кольца. Снимите одно перед тем, как надеть новое.',
    slotItemFull: 'Снимите надетый предмет перед тем, как надеть новый.',
    itemRemoved: '🗑️ Удалено',
    itemRemovedMsg: '«%1» выброшено. Оно исчезает в небытии...',
    itemSold: '🏪 Сделка совершена',
    itemSoldMsg: 'Вы продали «%1» за %2. Торговец довольно кивает.',
    chestEmpty: 'Сундук оказался пуст.',
    chestGray: 'Серый сундук',
    chestGold: 'Золотой сундук',
    chestGot: 'Вы получили: %1 (%2)',
    enterName: 'Введите название!',
    itemAdded: '«%1» добавлено.',
    // Notes
    notesTitle: '📝 Заметки',
    noNotes: 'Нет заметок',
    newNoteBtn: '➕ Новая заметка',
    // Dice
    diceTitle: '🎲 Броски кубиков',
    diceType: 'Тип кубика:',
    diceCount: 'Количество бросков:',
    diceRollType: 'Тип броска:',
    diceNormal: 'Нормальный',
    diceAdvantage: 'С преимуществом',
    diceDisadvantage: 'С помехой',
    rollBtn: '🎲 Бросить!',
    // Chat
    chatTitle: '📖 ИИ‑Мастер',
    chatPlaceholder: 'Спросите Мастера о правилах, вашем персонаже, монстрах...',
    chatThinking: 'Мастер размышляет...',
    chatNoInternet: '❌ Нет интернета',
    chatNetworkError: '❌ Ошибка сети. Проверьте интернет.',
    chatApiError: '❌ Ошибка API: %1',
    sendBtn: '➤',
    // Proficiency
    bonusProficiency: 'Бонус мастерства для %1 уровня: +%2',
    // Custom item modal
    createRecord: '📦 Создать запись',
    customName: 'Название',
    customNote: '📝 Заметка',
    customWeapon: '⚔️ Оружие',
    customArmor: '🛡️ Доспех',
    customArtifact: '💍 Артефакт',
    customDesc: 'Описание (необязательно)',
    customCreate: '➕ Создать',
    customNoSlot: 'Без слота',
    // Stats
    statStr: 'Сила',
    statDex: 'Ловк',
    statCon: 'Тел',
    statInt: 'Инт',
    statWis: 'Мудр',
    statCha: 'Хар',
    statStrFull: 'Сила',
    statDexFull: 'Ловкость',
    statConFull: 'Телосложение',
    statIntFull: 'Интеллект',
    statWisFull: 'Мудрость',
    statChaFull: 'Харизма',
    base: 'База',
    racial: 'Раса',
    item: 'Предм',
    temp: 'Врем',
    // Spell modal
    spellsModalTitle: 'Выберите способности',
    spellsAllLevels: 'Все уровни',
    spellsCantrips: 'Заговоры (0)',
    spellsLevel: '%1 уровень',
    spellsAllSchools: 'Все школы',
    spellsSearch: '🔍 Поиск способностей...',
    spellsNotFound: 'Способности не найдены.',
    spellsFound: 'Найдено: %1',
    spellAdded: '✓ Добавлено',
    spellAdd: '+ Добавить',
    createAbility: '➕ Создать способность',
    abilityName: 'Название способности',
    abilityLevel: 'Уровень',
    abilityDesc: 'Описание',
    // Race/Class details
    raceModalTitle: 'Особенности расы',
    classModalTitle: 'Особенности класса',
    raceNotSelected: 'Раса не выбрана',
    raceNoDesc: 'Нет описания',
    classNotSelected: 'Класс не выбран.',
    classNoDetails: 'Подробности временно отсутствуют.',
    classFeatures: '📋 Особенности класса',
    languages: 'Языки',
    // Mini card
    miniCardHint: 'Нажмите для полной карточки',
    // Misc
    inventoryEmpty: '🎒 Инвентарь пуст',
    ft: 'фт',
    attack: 'Атака',
    damage: 'Урон',
    // Skills
    skillsManageProficiency: '⚙️ Управление владением',
    skillsProficiencyTitle: 'Владение навыками',
    skillsSaveProficiency: '💾 Сохранить',
    skillAddTemp: 'Временный бонус',
    skillTempValue: 'Значение бонуса (например, +2 или +1d4 = 2):',
    skillApplyTemp: '✓ Применить',
    skillClearTemp: '✕ Убрать',
    skill_acrobatics: 'Акробатика',
    skill_athletics: 'Атлетика',
    skill_perception: 'Внимательность',
    skill_survival: 'Выживание',
    skill_intimidation: 'Запугивание',
    skill_history: 'История',
    skill_sleightOfHand: 'Ловкость рук',
    skill_arcana: 'Магия',
    skill_medicine: 'Медицина',
    skill_deception: 'Обман',
    skill_animalHandling: 'Обращение с животными',
    skill_insight: 'Проницательность',
    skill_religion: 'Религия',
    skill_stealth: 'Скрытность',
    skill_persuasion: 'Убеждение',
    skill_investigation: 'Хитрость',
    skill_performance: 'Цирковое искусство',
    skill_nature: 'Эрудиция',
    statAbbr_str: 'Сил',
    statAbbr_dex: 'Ловк',
    statAbbr_con: 'Тел',
    statAbbr_int: 'Инт',
    statAbbr_wis: 'Мудр',
    statAbbr_cha: 'Хар',
    // Wizard
    wizardStep1: 'Имя и раса',
    wizardStep2: 'Класс',
    wizardStep3: 'Характ.',
    wizardStep4: 'Способн.',
    wizardStep5: 'Снаряж.',
    wizardStepOf: 'Шаг %1 из %2',
    wizardNext: 'Далее',
    wizardPrev: 'Назад',
    // PDF
    pdfExport: 'Экспорт в PDF',
    pdfExporting: 'Генерация PDF...',
    // Rarity
    rarityCommon: 'Обычный',
    rarityUncommon: 'Необычный',
    rarityRare: 'Редкий',
    rarityVeryRare: 'Очень редкий',
    rarityLegendary: 'Легендарный',
    rarityScaling: 'Масштабирующийся',
    // Stats info modal
    statsInfoTitle: 'Как работают характеристики',
    statsInfoPointBuy: 'Point Buy (27 очков)',
    statsInfoPointBuyText: 'Все характеристики начинаются с 8. Вы можете повышать их, тратя очки:\n• 9 → 1 очко, 10 → 2, 11 → 3, 12 → 4, 13 → 5\n• 14 → 7 очков, 15 → 9 очков\nВсего доступно 27 очков.',
    statsInfoASI: 'Повышение от уровня (ASI)',
    statsInfoASIText: 'На уровнях 4, 8, 12, 16 и 19 вы получаете +2 дополнительных очка. Ими можно поднять характеристику выше 15 (до максимума 20).',
    statsInfoRacial: 'Расовые бонусы',
    statsInfoRacialText: 'Каждая раса даёт бонусы к определённым характеристикам. Они прибавляются сверху и не тратят ваши очки.',
    statsInfoRandom: 'Случайное распределение',
    statsInfoRandomText: 'Кнопка Случайно автоматически распределяет все 27 очков + очки ASI случайным образом, создавая сбалансированный набор характеристик.',
    statsInfoModifier: 'Модификатор',
    statsInfoModifierText: 'Модификатор = (Итоговая характеристика − 10) ÷ 2 (округление вниз). Он используется для бросков атаки, спасбросков и проверок навыков.',
    // Custom creators
    createCustomRace: '➕ Создать свою расу',
    createCustomClass: '➕ Создать свой класс',
    customRaceTitle: '🧬 Создать расу',
    customClassTitle: '⚔️ Создать класс',
    customRaceName: 'Название расы',
    customRaceDesc: 'Описание расы',
    customRaceBonuses: 'Бонусы характеристик:',
    customRaceLanguages: 'Языки (через запятую)',
    customRaceFeatures: 'Особенности:',
    addFeature: '➕ Добавить особенность',
    saveCustomRace: '💾 Сохранить расу',
    customClassName: 'Название класса',
    customClassDesc: 'Описание класса',
    customClassHitDie: 'Кость хитов',
    customClassSubLevel: 'Подкласс на ур.',
    customClassPrimary: 'Основная характеристика (напр. Сила и Ловкость)',
    customClassFeatures: 'Особенности по уровням:',
    addClassFeature: '➕ Добавить особенность',
    customClassSubclasses: 'Подклассы:',
    addSubclass: '➕ Добавить подкласс',
    saveCustomClass: '💾 Сохранить класс',
    // Level
    levelN: '%1 уровень',
    // Chat system
    chatSystemPromptDefault: 'Ты — опытный Мастер подземелий D&D 5e. Отвечай на русском языке дружелюбно и увлекательно.',
    chatSystemPromptFull: 'Ты — ИИ‑Мастер D&D 5e.\nПерсонаж игрока:\n- Имя: %1\n- Раса: %2\n- Класс: %3 (уровень %4)\n- Сила: %5\n- Ловкость: %6\n- Телосложение: %7\n- Интеллект: %8\n- Мудрость: %9\n- Харизма: %10\n\nОтвечай на русском, как настоящий Мастер Подземелий — с атмосферой, описаниями и полезными советами по D&D 5e.',
    // Alert button
    cancelBtn: 'Отмена',
    okBtn: 'OK',
    // Misc labels
    unnamed: 'Безымянный',
    notification: 'Уведомление',
    levelWord: 'Уровень',
    subclassWord: '(подкласс)',
    levelCard: 'Уровень %1',
    total: 'Всего',
    countWeapon: '⚔️',
    countArmor: '🛡️',
    countArtifact: '💍',
    // Spell schools (for filter)
    schoolEvocation: 'Воплощение',
    schoolNecromancy: 'Некромантия',
    schoolIllusion: 'Иллюзия',
    schoolEnchantment: 'Очарование',
    schoolAbjuration: 'Ограждение',
    schoolTransmutation: 'Преобразование',
    schoolDivination: 'Прорицание',
    schoolConjuration: 'Вызов',
    schoolSpecial: 'Особая',
    // Spell types
    spellTypeAll: 'Все типы',
    spellTypeAttack: 'Атакующие',
    spellTypeDefense: 'Защитные',
    spellTypeHealing: 'Лечащие',
    spellTypeBuff: 'Баффы',
    spellTypeSummon: 'Призывающие',
    spellTypeUtility: 'Универсальные',
    // NPC / Enemies
    btnNpcs: '👹 NPC и враги',
    npcListTitle: '👹 NPC и враги',
    npcCreateBtn: '➕ Создать NPC',
    npcCreationTitle: '👹 Создание NPC / Врага',
    npcEditTitle: '👹 Редактирование NPC',
    npcName: 'Имя',
    npcNamePlaceholder: 'Введите имя NPC',
    npcLevel: 'Уровень',
    npcHP: 'Здоровье (HP)',
    npcStats: 'Характеристики',
    npcPersonality: 'Характер / Личность',
    npcPersonalitySelect: '-- Выберите характер --',
    npcPersonalityCustom: 'Или введите свой...',
    npcWorldview: 'Мировоззрение',
    npcWorldviewSelect: '-- Выберите мировоззрение --',
    npcWorldviewCustom: 'Или введите своё...',
    npcProfession: 'Профессия',
    npcProfessionSelect: '-- Выберите профессию --',
    npcProfessionCustom: 'Или введите свою...',
    npcWeapon: 'Оружие',
    npcWeaponSelect: '-- Выберите оружие --',
    npcWeaponCustom: 'Или введите своё...',
    npcAppearance: 'Внешний вид',
    npcAppearanceSelect: '-- Выберите внешность --',
    npcAppearanceCustom: 'Или введите своё описание...',
    npcEquipment: 'Снаряжение (фиксированное)',
    npcEquipmentHint: 'Снаряжение нельзя будет изменить после создания',
    npcEquipmentSlot: 'Слот: %1',
    npcEquipmentItemPlaceholder: 'Предмет для слота...',
    npcSave: '💾 Сохранить NPC',
    npcSaved: 'NPC «%1» сохранён!',
    npcDeleted: 'NPC удалён',
    npcConfirmDelete: 'Удалить этого NPC?',
    npcNoItems: 'Нет созданных NPC',
    npcQuickCardTitle: '👹 Карточка NPC',
    npcQuickEditHint: 'Можно изменить: уровень, HP, характеристики',
    npcEquipmentFixed: 'Снаряжение (неизменяемое)',
    npcFullEdit: '✏️ Полное редактирование',
    npcDeleteBtn: '🗑️ Удалить',
    npcBackToList: '← К списку NPC',
    npcValidationName: 'Введите имя NPC!',
    npcValidationLevel: 'Уровень должен быть числом от 1 до 30!',
    npcValidationHP: 'HP должен быть числом больше 0!',
    npcCustomValue: 'Своё значение',
    npcRandomBtn: 'Случайно',
    // NPC Personalities
    npcPers_aggressive: 'Агрессивный',
    npcPers_friendly: 'Дружелюбный',
    npcPers_cautious: 'Осторожный',
    npcPers_cunning: 'Хитрый',
    npcPers_cowardly: 'Трусливый',
    npcPers_brave: 'Храбрый',
    npcPers_greedy: 'Жадный',
    npcPers_generous: 'Щедрый',
    npcPers_mysterious: 'Загадочный',
    npcPers_loyal: 'Верный',
    npcPers_cruel: 'Жестокий',
    npcPers_kind: 'Добрый',
    npcPers_mad: 'Безумный',
    npcPers_calm: 'Спокойный',
    npcPers_arrogant: 'Высокомерный',
    npcPers_humble: 'Скромный',
    // NPC Worldviews
    npcWv_lawful_good: 'Законно-добрый',
    npcWv_neutral_good: 'Нейтрально-добрый',
    npcWv_chaotic_good: 'Хаотично-добрый',
    npcWv_lawful_neutral: 'Законно-нейтральный',
    npcWv_true_neutral: 'Истинно нейтральный',
    npcWv_chaotic_neutral: 'Хаотично-нейтральный',
    npcWv_lawful_evil: 'Законно-злой',
    npcWv_neutral_evil: 'Нейтрально-злой',
    npcWv_chaotic_evil: 'Хаотично-злой',
    // NPC Professions
    npcProf_trader: 'Торговец',
    npcProf_warrior: 'Воин',
    npcProf_officer: 'Офицер',
    npcProf_leader: 'Глава',
    npcProf_boss: 'Босс',
    npcProf_baron: 'Барон',
    npcProf_thief: 'Вор',
    npcProf_assassin: 'Убийца',
    npcProf_mage: 'Маг',
    npcProf_healer: 'Целитель',
    npcProf_blacksmith: 'Кузнец',
    npcProf_innkeeper: 'Трактирщик',
    npcProf_guard: 'Стражник',
    npcProf_mercenary: 'Наёмник',
    npcProf_priest: 'Жрец',
    npcProf_noble: 'Дворянин',
    npcProf_peasant: 'Крестьянин',
    npcProf_bandit: 'Бандит',
    npcProf_scout: 'Разведчик',
    npcProf_necromancer: 'Некромант',
    npcProf_king: 'Король',
    npcProf_knight: 'Рыцарь',
    npcProf_monk_npc: 'Монах',
    npcProf_bard_npc: 'Бард',
    // NPC Weapons
    npcWpn_sword: 'Меч',
    npcWpn_longsword: 'Длинный меч',
    npcWpn_greatsword: 'Двуручный меч',
    npcWpn_dagger: 'Кинжал',
    npcWpn_axe: 'Топор',
    npcWpn_greataxe: 'Секира',
    npcWpn_mace: 'Булава',
    npcWpn_warhammer: 'Боевой молот',
    npcWpn_spear: 'Копьё',
    npcWpn_halberd: 'Алебарда',
    npcWpn_bow: 'Лук',
    npcWpn_longbow: 'Длинный лук',
    npcWpn_crossbow: 'Арбалет',
    npcWpn_staff: 'Посох',
    npcWpn_wand: 'Жезл',
    npcWpn_claws: 'Когти',
    npcWpn_bite: 'Укус',
    npcWpn_fists: 'Кулаки',
    npcWpn_whip: 'Плеть',
    npcWpn_scimitar: 'Ятаган',
    npcWpn_rapier: 'Рапира',
    npcWpn_trident: 'Трезубец',
    npcWpn_flail: 'Цеп',
    // NPC Appearances
    npcApp_tall_muscular: 'Высокий и мускулистый',
    npcApp_short_stocky: 'Низкий и коренастый',
    npcApp_thin_pale: 'Худой и бледный',
    npcApp_scarred: 'Покрытый шрамами',
    npcApp_hooded: 'В капюшоне',
    npcApp_armored: 'В тяжёлых доспехах',
    npcApp_robed: 'В мантии',
    npcApp_elegant: 'Элегантный',
    npcApp_dirty_ragged: 'Грязный и оборванный',
    npcApp_old_wise: 'Старый и мудрый',
    npcApp_young_agile: 'Молодой и ловкий',
    npcApp_monstrous: 'Чудовищный',
    npcApp_beautiful: 'Красивый',
    npcApp_intimidating: 'Устрашающий',
    npcApp_average: 'Обычный',
    npcApp_tattooed: 'Покрытый татуировками',
    npcApp_one_eyed: 'Одноглазый',
    npcApp_huge: 'Огромный',
    // Audio Library
    btnAudio: '🎵 Аудиотека',
    audioTitle: '🎵 Аудиотека',
    audioUpload: '📂 Загрузить аудио',
    audioEmpty: 'Аудиотека пуста. Загрузите файлы (mp3, wav, ogg).',
    audioPlay: '▶️ Воспроизвести',
    audioPause: '⏸️ Пауза',
    audioStop: '⏹️ Стоп',
    audioDelete: '🗑️ Удалить',
    audioDeleteConfirm: 'Удалить этот аудиофайл?',
    audioDeleted: 'Аудиофайл удалён',
    audioBind: '🔗 Привязать',
    audioUnbind: '✂️ Открепить',
    audioBindTo: 'Привязать к...',
    audioBindCharacter: 'Персонаж',
    audioBindNpc: 'NPC',
    audioBindSelect: '-- Выберите --',
    audioBound: 'Привязано к: %1',
    audioNoBound: 'Не привязано',
    audioVolume: 'Громкость',
    audioFileError: 'Ошибка: неверный формат файла. Поддерживаются mp3, wav, ogg.',
    audioLoadError: 'Ошибка загрузки аудио',
    audioPermissionError: 'Нет доступа к файлам. Предоставьте разрешение.',
    audioTheme: '🎵 Тема',
    audioBackToList: '← К списку',
    // Avatar
    avatarTitle: 'Аватар',
    avatarSelect: '📷 Выбрать из галереи',
    avatarCamera: '📸 Сделать фото',
    avatarDelete: '🗑️ Удалить аватар',
    avatarDeleteConfirm: 'Удалить аватар персонажа?',
    avatarDeleted: 'Аватар удалён',
    avatarUpdated: 'Аватар обновлён',
    avatarError: 'Ошибка загрузки изображения',
    avatarPermissionError: 'Нет доступа к камере/галерее. Предоставьте разрешение.',
    avatarChange: '🔄 Сменить аватар',
  },
  en: {
    // Menu
    mainTitle: 'Roll Assistant',
    mainSubtitle: 'Create your hero',
    btnCreate: '✨ Create Character',
    btnQuickStart: '⚡ Quick Start',
    btnCharacters: '👥 My Characters',
    // Creation screen
    creationTitle: '🧙 Character Creation',
    back: '← Back',
    saveCharacter: '💾 Save Character',
    nameLabel: 'Character Name',
    namePlaceholder: 'Enter name',
    raceLabel: 'Race',
    raceSelect: '-- Choose a race --',
    raceDetails: '🔍 Race Details',
    classLabel: 'Class',
    classSelect: '-- Choose a class --',
    classDetails: '🔍 Class Details',
    subclassLabel: 'Archetype (Subclass)',
    subclassSelect: '-- Choose an archetype --',
    levelLabel: 'Character Level',
    statsLabel: 'Ability Scores',
    statsInfoBtn: '?⃝',
    pointsDisplay: 'Points: %1 (base), +%2 from levels',
    randomStats: '🎲 Random',
    resetStats: '🔄 Reset to 8',
    abilitiesLabel: '📜 Spells & Abilities',
    abilitiesSummary: 'Not selected',
    abilitiesSelected: 'Selected: %1',
    btnOpenSpells: 'Select Spells',
    equipmentLabel: '⚔️ Equipment & Artifacts',
    equipSearch: '🔍 Find item...',
    equipAllTypes: 'All types',
    equipWeapon: '⚔️ Weapon',
    equipArmor: '🛡️ Armor',
    equipArtifact: '💍 Artifact',
    equipAllRarities: 'All rarities',
    equipSelectItem: '-- Choose an item --',
    // Sheet
    sheetTitle: '📋 Character Sheet',
    sheetIdentity: 'Identity',
    sheetRace: 'Race',
    sheetClass: 'Class',
    sheetLevelHP: 'Level & Hit Points',
    sheetLevel: 'Level',
    sheetMaxHP: 'Max HP',
    sheetExp: 'Experience',
    sheetAbilities: 'Ability Scores',
    sheetCombat: 'Combat Parameters',
    sheetHP: 'HP',
    sheetAC: 'AC',
    sheetInitiative: 'Initiative',
    sheetSpeed: 'Speed',
    sheetProfBonus: 'Proficiency Bonus',
    sheetSaves: 'Saving Throws',
    sheetSkills: 'Skills',
    sheetSkillsWip: 'In development',
    sheetEquipment: 'Equipment',
    sheetEquipBonuses: '✨ Item Bonuses',
    sheetBackpack: '🎒 Backpack',
    sheetSpells: 'Abilities',
    sheetSelectSpells: '📜 Select Abilities',
    sheetNoEquipped: 'No equipped items',
    sheetNoSpells: 'No abilities selected',
    sheetBackpackEmpty: 'Backpack is empty',
    // Equipment slots
    slotHead: 'Head',
    slotBody: 'Body',
    slotMainhand: 'Main Hand',
    slotOffhand: 'Off Hand',
    slotFeet: 'Feet',
    slotRing: 'Ring',
    slotNeck: 'Neck',
    slotBack: 'Back',
    slotHands: 'Hands',
    slotWaist: 'Waist',
    // Backpack
    coinCopper: 'Copper',
    coinSilver: 'Silver',
    coinGold: 'Gold',
    coinDiamond: 'Diamonds',
    grayChest: '🗝️ Gray Chest',
    goldChest: '🔱 Gold Chest',
    addRecord: '📝 Add Record',
    btnEquip: 'Equip',
    btnUnequip: 'Unequip',
    // Characters list
    charactersListTitle: '👥 My Characters',
    noSaved: 'No saved characters',
    setMain: '⭐ Set as Main',
    deleteChar: '🗑️ Delete',
    mainBadge: '⭐ Main',
    // Alerts
    charSaved: 'Character "%1" saved!',
    success: 'Success',
    error: 'Error',
    confirm: 'Confirmation',
    loaded: 'Loaded',
    done: 'Done',
    quickStartConfirm: '6 balanced level-1 characters with weapons, armor and abilities will be created. Continue?',
    quickStartDone: '6 characters added to "My Characters". The last one is set as main.',
    errorSelectRaceClass: 'Please select a race and class first!',
    confirmDelete: 'Delete this character?',
    charLoaded: 'Character loaded as main!',
    mainChanged: 'Main character changed!',
    slotOccupied: 'Slot Occupied',
    slotRingFull: 'Already wearing two rings. Remove one before equipping a new one.',
    slotItemFull: 'Remove the equipped item before equipping a new one.',
    itemRemoved: '🗑️ Removed',
    itemRemovedMsg: '"%1" discarded. It vanishes into the void...',
    itemSold: '🏪 Deal Complete',
    itemSoldMsg: 'You sold "%1" for %2. The merchant nods approvingly.',
    chestEmpty: 'The chest was empty.',
    chestGray: 'Gray Chest',
    chestGold: 'Gold Chest',
    chestGot: 'You received: %1 (%2)',
    enterName: 'Enter a name!',
    itemAdded: '"%1" added.',
    // Notes
    notesTitle: '📝 Notes',
    noNotes: 'No notes',
    newNoteBtn: '➕ New Note',
    // Dice
    diceTitle: '🎲 Dice Roller',
    diceType: 'Dice type:',
    diceCount: 'Number of rolls:',
    diceRollType: 'Roll type:',
    diceNormal: 'Normal',
    diceAdvantage: 'Advantage',
    diceDisadvantage: 'Disadvantage',
    rollBtn: '🎲 Roll!',
    // Chat
    chatTitle: '📖 AI Dungeon Master',
    chatPlaceholder: 'Ask the Master about rules, your character, monsters...',
    chatThinking: 'The Master is thinking...',
    chatNoInternet: '❌ No internet connection',
    chatNetworkError: '❌ Network error. Check your connection.',
    chatApiError: '❌ API Error: %1',
    sendBtn: '➤',
    // Proficiency
    bonusProficiency: 'Proficiency bonus for level %1: +%2',
    // Custom item modal
    createRecord: '📦 Create Record',
    customName: 'Name',
    customNote: '📝 Note',
    customWeapon: '⚔️ Weapon',
    customArmor: '🛡️ Armor',
    customArtifact: '💍 Artifact',
    customDesc: 'Description (optional)',
    customCreate: '➕ Create',
    customNoSlot: 'No slot',
    // Stats
    statStr: 'Str',
    statDex: 'Dex',
    statCon: 'Con',
    statInt: 'Int',
    statWis: 'Wis',
    statCha: 'Cha',
    statStrFull: 'Strength',
    statDexFull: 'Dexterity',
    statConFull: 'Constitution',
    statIntFull: 'Intelligence',
    statWisFull: 'Wisdom',
    statChaFull: 'Charisma',
    base: 'Base',
    racial: 'Race',
    item: 'Item',
    temp: 'Temp',
    // Spell modal
    spellsModalTitle: 'Select Abilities',
    spellsAllLevels: 'All levels',
    spellsCantrips: 'Cantrips (0)',
    spellsLevel: 'Level %1',
    spellsAllSchools: 'All schools',
    spellsSearch: '🔍 Search abilities...',
    spellsNotFound: 'No abilities found.',
    spellsFound: 'Found: %1',
    spellAdded: '✓ Added',
    spellAdd: '+ Add',
    createAbility: '➕ Create Ability',
    abilityName: 'Ability name',
    abilityLevel: 'Level',
    abilityDesc: 'Description',
    // Race/Class details
    raceModalTitle: 'Race Features',
    classModalTitle: 'Class Features',
    raceNotSelected: 'No race selected',
    raceNoDesc: 'No description available',
    classNotSelected: 'No class selected.',
    classNoDetails: 'Details temporarily unavailable.',
    classFeatures: '📋 Class Features',
    languages: 'Languages',
    // Mini card
    miniCardHint: 'Tap for full character sheet',
    // Misc
    inventoryEmpty: '🎒 Inventory is empty',
    ft: 'ft',
    attack: 'Attack',
    damage: 'Damage',
    // Skills
    skillsManageProficiency: '⚙️ Manage Proficiencies',
    skillsProficiencyTitle: 'Skill Proficiencies',
    skillsSaveProficiency: '💾 Save',
    skillAddTemp: 'Temporary bonus',
    skillTempValue: 'Bonus value (e.g. +2 or +1d4 = 2):',
    skillApplyTemp: '✓ Apply',
    skillClearTemp: '✕ Remove',
    skill_acrobatics: 'Acrobatics',
    skill_athletics: 'Athletics',
    skill_perception: 'Perception',
    skill_survival: 'Survival',
    skill_intimidation: 'Intimidation',
    skill_history: 'History',
    skill_sleightOfHand: 'Sleight of Hand',
    skill_arcana: 'Arcana',
    skill_medicine: 'Medicine',
    skill_deception: 'Deception',
    skill_animalHandling: 'Animal Handling',
    skill_insight: 'Insight',
    skill_religion: 'Religion',
    skill_stealth: 'Stealth',
    skill_persuasion: 'Persuasion',
    skill_investigation: 'Investigation',
    skill_performance: 'Performance',
    skill_nature: 'Nature',
    statAbbr_str: 'Str',
    statAbbr_dex: 'Dex',
    statAbbr_con: 'Con',
    statAbbr_int: 'Int',
    statAbbr_wis: 'Wis',
    statAbbr_cha: 'Cha',
    // Wizard
    wizardStep1: 'Name & Race',
    wizardStep2: 'Class',
    wizardStep3: 'Scores',
    wizardStep4: 'Abilities',
    wizardStep5: 'Equip',
    wizardStepOf: 'Step %1 of %2',
    wizardNext: 'Next',
    wizardPrev: 'Back',
    // PDF
    pdfExport: 'Export to PDF',
    pdfExporting: 'Generating PDF...',
    // Rarity
    rarityCommon: 'Common',
    rarityUncommon: 'Uncommon',
    rarityRare: 'Rare',
    rarityVeryRare: 'Very Rare',
    rarityLegendary: 'Legendary',
    rarityScaling: 'Scaling',
    // Stats info modal
    statsInfoTitle: 'How Ability Scores Work',
    statsInfoPointBuy: 'Point Buy (27 points)',
    statsInfoPointBuyText: 'All ability scores start at 8. You can increase them by spending points:\n• 9 → 1 point, 10 → 2, 11 → 3, 12 → 4, 13 → 5\n• 14 → 7 points, 15 → 9 points\nTotal: 27 points available.',
    statsInfoASI: 'Ability Score Improvement (ASI)',
    statsInfoASIText: 'At levels 4, 8, 12, 16, and 19, you gain +2 additional points. These can raise a score above 15 (up to a maximum of 20).',
    statsInfoRacial: 'Racial Bonuses',
    statsInfoRacialText: 'Each race grants bonuses to certain ability scores. They are added on top and do not cost any of your points.',
    statsInfoRandom: 'Random Distribution',
    statsInfoRandomText: 'The Random button automatically distributes all 27 points + ASI points randomly, creating a balanced set of ability scores.',
    statsInfoModifier: 'Modifier',
    statsInfoModifierText: 'Modifier = (Final Score − 10) ÷ 2 (rounded down). It is used for attack rolls, saving throws, and ability checks.',
    // Custom creators
    createCustomRace: '➕ Create Custom Race',
    createCustomClass: '➕ Create Custom Class',
    customRaceTitle: '🧬 Create Race',
    customClassTitle: '⚔️ Create Class',
    customRaceName: 'Race name',
    customRaceDesc: 'Race description',
    customRaceBonuses: 'Ability score bonuses:',
    customRaceLanguages: 'Languages (comma-separated)',
    customRaceFeatures: 'Features:',
    addFeature: '➕ Add Feature',
    saveCustomRace: '💾 Save Race',
    customClassName: 'Class name',
    customClassDesc: 'Class description',
    customClassHitDie: 'Hit Die',
    customClassSubLevel: 'Subclass at lvl',
    customClassPrimary: 'Primary ability (e.g. Strength and Dexterity)',
    customClassFeatures: 'Features by level:',
    addClassFeature: '➕ Add Feature',
    customClassSubclasses: 'Subclasses:',
    addSubclass: '➕ Add Subclass',
    saveCustomClass: '💾 Save Class',
    // Level
    levelN: 'Level %1',
    // Chat system
    chatSystemPromptDefault: 'You are an experienced D&D 5e Dungeon Master. Answer in English in a friendly and engaging way.',
    chatSystemPromptFull: 'You are an AI Dungeon Master for D&D 5e.\nPlayer character:\n- Name: %1\n- Race: %2\n- Class: %3 (level %4)\n- Strength: %5\n- Dexterity: %6\n- Constitution: %7\n- Intelligence: %8\n- Wisdom: %9\n- Charisma: %10\n\nAnswer in English like a real Dungeon Master — with atmosphere, descriptions and useful D&D 5e tips.',
    // Alert button
    cancelBtn: 'Cancel',
    okBtn: 'OK',
    // Misc labels
    unnamed: 'Unnamed',
    notification: 'Notification',
    levelWord: 'Level',
    subclassWord: '(subclass)',
    levelCard: 'Level %1',
    total: 'Total',
    countWeapon: '⚔️',
    countArmor: '🛡️',
    countArtifact: '💍',
    // Spell schools (for filter)
    schoolEvocation: 'Evocation',
    schoolNecromancy: 'Necromancy',
    schoolIllusion: 'Illusion',
    schoolEnchantment: 'Enchantment',
    schoolAbjuration: 'Abjuration',
    schoolTransmutation: 'Transmutation',
    schoolDivination: 'Divination',
    schoolConjuration: 'Conjuration',
    schoolSpecial: 'Special',
    // Spell types
    spellTypeAll: 'All types',
    spellTypeAttack: 'Attack',
    spellTypeDefense: 'Defense',
    spellTypeHealing: 'Healing',
    spellTypeBuff: 'Buff',
    spellTypeSummon: 'Summon',
    spellTypeUtility: 'Utility',
    // NPC / Enemies
    btnNpcs: '👹 NPCs & Enemies',
    npcListTitle: '👹 NPCs & Enemies',
    npcCreateBtn: '➕ Create NPC',
    npcCreationTitle: '👹 Create NPC / Enemy',
    npcEditTitle: '👹 Edit NPC',
    npcName: 'Name',
    npcNamePlaceholder: 'Enter NPC name',
    npcLevel: 'Level',
    npcHP: 'Health (HP)',
    npcStats: 'Ability Scores',
    npcPersonality: 'Personality',
    npcPersonalitySelect: '-- Choose personality --',
    npcPersonalityCustom: 'Or enter custom...',
    npcWorldview: 'Alignment',
    npcWorldviewSelect: '-- Choose alignment --',
    npcWorldviewCustom: 'Or enter custom...',
    npcProfession: 'Profession',
    npcProfessionSelect: '-- Choose profession --',
    npcProfessionCustom: 'Or enter custom...',
    npcWeapon: 'Weapon',
    npcWeaponSelect: '-- Choose weapon --',
    npcWeaponCustom: 'Or enter custom...',
    npcAppearance: 'Appearance',
    npcAppearanceSelect: '-- Choose appearance --',
    npcAppearanceCustom: 'Or enter custom description...',
    npcEquipment: 'Equipment (fixed)',
    npcEquipmentHint: 'Equipment cannot be changed after creation',
    npcEquipmentSlot: 'Slot: %1',
    npcEquipmentItemPlaceholder: 'Item for slot...',
    npcSave: '💾 Save NPC',
    npcSaved: 'NPC "%1" saved!',
    npcDeleted: 'NPC deleted',
    npcConfirmDelete: 'Delete this NPC?',
    npcNoItems: 'No NPCs created',
    npcQuickCardTitle: '👹 NPC Card',
    npcQuickEditHint: 'You can edit: level, HP, ability scores',
    npcEquipmentFixed: 'Equipment (immutable)',
    npcFullEdit: '✏️ Full Edit',
    npcDeleteBtn: '🗑️ Delete',
    npcBackToList: '← Back to NPC List',
    npcValidationName: 'Enter a name for the NPC!',
    npcValidationLevel: 'Level must be a number from 1 to 30!',
    npcValidationHP: 'HP must be a number greater than 0!',
    npcCustomValue: 'Custom value',
    npcRandomBtn: 'Random',
    // NPC Personalities
    npcPers_aggressive: 'Aggressive',
    npcPers_friendly: 'Friendly',
    npcPers_cautious: 'Cautious',
    npcPers_cunning: 'Cunning',
    npcPers_cowardly: 'Cowardly',
    npcPers_brave: 'Brave',
    npcPers_greedy: 'Greedy',
    npcPers_generous: 'Generous',
    npcPers_mysterious: 'Mysterious',
    npcPers_loyal: 'Loyal',
    npcPers_cruel: 'Cruel',
    npcPers_kind: 'Kind',
    npcPers_mad: 'Mad',
    npcPers_calm: 'Calm',
    npcPers_arrogant: 'Arrogant',
    npcPers_humble: 'Humble',
    // NPC Worldviews
    npcWv_lawful_good: 'Lawful Good',
    npcWv_neutral_good: 'Neutral Good',
    npcWv_chaotic_good: 'Chaotic Good',
    npcWv_lawful_neutral: 'Lawful Neutral',
    npcWv_true_neutral: 'True Neutral',
    npcWv_chaotic_neutral: 'Chaotic Neutral',
    npcWv_lawful_evil: 'Lawful Evil',
    npcWv_neutral_evil: 'Neutral Evil',
    npcWv_chaotic_evil: 'Chaotic Evil',
    // NPC Professions
    npcProf_trader: 'Trader',
    npcProf_warrior: 'Warrior',
    npcProf_officer: 'Officer',
    npcProf_leader: 'Leader',
    npcProf_boss: 'Boss',
    npcProf_baron: 'Baron',
    npcProf_thief: 'Thief',
    npcProf_assassin: 'Assassin',
    npcProf_mage: 'Mage',
    npcProf_healer: 'Healer',
    npcProf_blacksmith: 'Blacksmith',
    npcProf_innkeeper: 'Innkeeper',
    npcProf_guard: 'Guard',
    npcProf_mercenary: 'Mercenary',
    npcProf_priest: 'Priest',
    npcProf_noble: 'Noble',
    npcProf_peasant: 'Peasant',
    npcProf_bandit: 'Bandit',
    npcProf_scout: 'Scout',
    npcProf_necromancer: 'Necromancer',
    npcProf_king: 'King',
    npcProf_knight: 'Knight',
    npcProf_monk_npc: 'Monk',
    npcProf_bard_npc: 'Bard',
    // NPC Weapons
    npcWpn_sword: 'Sword',
    npcWpn_longsword: 'Longsword',
    npcWpn_greatsword: 'Greatsword',
    npcWpn_dagger: 'Dagger',
    npcWpn_axe: 'Axe',
    npcWpn_greataxe: 'Greataxe',
    npcWpn_mace: 'Mace',
    npcWpn_warhammer: 'Warhammer',
    npcWpn_spear: 'Spear',
    npcWpn_halberd: 'Halberd',
    npcWpn_bow: 'Bow',
    npcWpn_longbow: 'Longbow',
    npcWpn_crossbow: 'Crossbow',
    npcWpn_staff: 'Staff',
    npcWpn_wand: 'Wand',
    npcWpn_claws: 'Claws',
    npcWpn_bite: 'Bite',
    npcWpn_fists: 'Fists',
    npcWpn_whip: 'Whip',
    npcWpn_scimitar: 'Scimitar',
    npcWpn_rapier: 'Rapier',
    npcWpn_trident: 'Trident',
    npcWpn_flail: 'Flail',
    // NPC Appearances
    npcApp_tall_muscular: 'Tall and muscular',
    npcApp_short_stocky: 'Short and stocky',
    npcApp_thin_pale: 'Thin and pale',
    npcApp_scarred: 'Scarred',
    npcApp_hooded: 'Hooded',
    npcApp_armored: 'Heavily armored',
    npcApp_robed: 'Robed',
    npcApp_elegant: 'Elegant',
    npcApp_dirty_ragged: 'Dirty and ragged',
    npcApp_old_wise: 'Old and wise',
    npcApp_young_agile: 'Young and agile',
    npcApp_monstrous: 'Monstrous',
    npcApp_beautiful: 'Beautiful',
    npcApp_intimidating: 'Intimidating',
    npcApp_average: 'Average',
    npcApp_tattooed: 'Tattooed',
    npcApp_one_eyed: 'One-eyed',
    npcApp_huge: 'Huge',
    // Audio Library
    btnAudio: '🎵 Audio Library',
    audioTitle: '🎵 Audio Library',
    audioUpload: '📂 Upload Audio',
    audioEmpty: 'Audio library is empty. Upload files (mp3, wav, ogg).',
    audioPlay: '▶️ Play',
    audioPause: '⏸️ Pause',
    audioStop: '⏹️ Stop',
    audioDelete: '🗑️ Delete',
    audioDeleteConfirm: 'Delete this audio file?',
    audioDeleted: 'Audio file deleted',
    audioBind: '🔗 Bind',
    audioUnbind: '✂️ Unbind',
    audioBindTo: 'Bind to...',
    audioBindCharacter: 'Character',
    audioBindNpc: 'NPC',
    audioBindSelect: '-- Select --',
    audioBound: 'Bound to: %1',
    audioNoBound: 'Not bound',
    audioVolume: 'Volume',
    audioFileError: 'Error: invalid file format. Supported: mp3, wav, ogg.',
    audioLoadError: 'Audio load error',
    audioPermissionError: 'No file access. Please grant permission.',
    audioTheme: '🎵 Theme',
    audioBackToList: '← Back',
    // Avatar
    avatarTitle: 'Avatar',
    avatarSelect: '📷 Choose from gallery',
    avatarCamera: '📸 Take photo',
    avatarDelete: '🗑️ Delete avatar',
    avatarDeleteConfirm: 'Delete character avatar?',
    avatarDeleted: 'Avatar deleted',
    avatarUpdated: 'Avatar updated',
    avatarError: 'Image load error',
    avatarPermissionError: 'No camera/gallery access. Please grant permission.',
    avatarChange: '🔄 Change avatar',
  }
};

let currentLang = localStorage.getItem('app-lang') || 'ru';
let reloadScheduled = false;

export function t(key, ...params) {
  const langObj = translations[currentLang] || translations.ru;
  let msg = langObj[key] || translations.ru[key] || key;
  for (let i = 0; i < params.length; i++) {
    msg = msg.replace(`%${i + 1}`, params[i]);
  }
  return msg;
}

export function setLanguage(lang) {
  if (reloadScheduled) return;
  if (!translations[lang]) lang = 'ru';
  currentLang = lang;
  localStorage.setItem('app-lang', lang);
  reloadScheduled = true;
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.remove('active-lang');
    if (btn.id === 'btn-lang-' + lang) {
      btn.classList.add('active-lang');
    }
  });
  setTimeout(() => location.reload(), 300);
}

export function getCurrentLang() {
  return currentLang;
}
